#!/usr/bin/env python3
"""
AI Frame - Project Initialization Wizard
Generates a CLAUDE.md master system prompt and .ai-frame/ context structure
for a coding project by asking targeted questions.

Usage:
    python init_project.py [--project-dir PATH]
"""

import argparse
import json
import os
import sys
from datetime import datetime
from pathlib import Path

# ─── Question Definitions ────────────────────────────────────────────────────

QUESTIONS = [
    {
        "key": "project_name",
        "label": "Project name",
        "type": "text",
    },
    {
        "key": "description",
        "label": "One-sentence description of what this project does",
        "type": "text",
    },
    {
        "key": "project_type",
        "label": "Project type",
        "type": "choice",
        "choices": [
            "web_app", "api_service", "cli_tool", "library",
            "data_pipeline", "mobile_app", "desktop_app", "other"
        ],
    },
    {
        "key": "language",
        "label": "Primary programming language",
        "type": "text",
        "placeholder": "e.g. Python, TypeScript, Go, Rust",
    },
    {
        "key": "runtime_version",
        "label": "Runtime / version",
        "type": "text",
        "optional": True,
        "placeholder": "e.g. Python 3.12, Node 20, Go 1.22  (leave blank to skip)",
    },
    {
        "key": "frameworks",
        "label": "Framework(s) in use",
        "type": "text",
        "optional": True,
        "placeholder": "e.g. FastAPI, React, Django  (leave blank if none)",
    },
    {
        "key": "architecture",
        "label": "Architecture style",
        "type": "choice",
        "choices": [
            "monolith", "microservices", "serverless", "mvc",
            "clean_architecture", "domain_driven_design",
            "event_driven", "layered", "other"
        ],
    },
    {
        "key": "testing_strategy",
        "label": "Testing strategy",
        "type": "choice",
        "choices": [
            "tdd", "unit_tests_only", "unit_and_integration",
            "e2e_focused", "bdd", "mixed", "minimal", "none"
        ],
    },
    {
        "key": "code_style",
        "label": "Code style / linting standard",
        "type": "text",
        "optional": True,
        "placeholder": "e.g. PEP8+Black, Airbnb ESLint, Google style, none",
    },
    {
        "key": "current_phase",
        "label": "Current project phase",
        "type": "choice",
        "choices": [
            "planning", "early_development", "active_development",
            "stabilisation", "testing", "maintenance", "refactoring"
        ],
    },
    {
        "key": "priorities",
        "label": "Top priorities (comma-separated)",
        "type": "text",
        "placeholder": "e.g. correctness, performance, readability, rapid iteration",
    },
    {
        "key": "constraints",
        "label": "Hard constraints or rules to always follow",
        "type": "text",
        "optional": True,
        "placeholder": "e.g. no external APIs, GDPR compliant, offline-first, zero downtime deploys",
    },
    {
        "key": "avoid",
        "label": "Patterns / approaches to AVOID",
        "type": "text",
        "optional": True,
        "placeholder": "e.g. global mutable state, deep inheritance, sync I/O in hot paths",
    },
    {
        "key": "team_size",
        "label": "Team size",
        "type": "choice",
        "choices": ["solo", "2-3_people", "4-8_people", "8+_people"],
    },
    {
        "key": "extra_context",
        "label": "Anything else Claude should always know about this project",
        "type": "text",
        "optional": True,
        "placeholder": "e.g. integrates with legacy system, security-sensitive domain, bilingual codebase",
    },
]

# ─── Prompt Templates ─────────────────────────────────────────────────────────

CLAUDE_MD_TEMPLATE = """\
# {project_name} — Master System Prompt

> Auto-generated by AI Frame on {date}. Edit freely.
> Context files live in `.ai-frame/`. Run `session_manager.py` to manage sessions.

## Project Overview

- **Name:** {project_name}
- **Type:** {project_type}
- **Language:** {language}{runtime_line}
- **Framework(s):** {frameworks}
- **Architecture:** {architecture}
- **Phase:** {current_phase}
- **Team:** {team_size}

{description}

## Priorities & Goals

{priorities_block}

## Coding Standards

- **Testing:** {testing_strategy}
- **Style guide:** {code_style}
- Always write code that is consistent with the existing codebase conventions.
- Prefer clarity over cleverness. Code is read far more than it is written.
- Keep functions small and focused on a single responsibility.
- Name things explicitly — avoid abbreviations unless they are domain-standard.

## Hard Constraints

{constraints_block}

## Patterns to Avoid

{avoid_block}

## Architecture Principles

Follow **{architecture}** patterns throughout. Specifically:
- Separate concerns at module/package boundaries.
- Favour composition over inheritance.
- Keep dependencies explicit and minimal.
- Side-effects belong at the edges of the system.

## Response Behaviour

- Be concise. Prefer short responses unless depth is explicitly needed.
- When suggesting code, match the project's language, style, and naming conventions.
- Before proposing a refactor or new pattern, confirm it fits the architecture above.
- Flag breaking changes, security implications, or constraint violations explicitly.
- If uncertain about intent, ask one focused clarifying question rather than assuming.

## Session Context

At the start of each session:
1. Read `.ai-frame/progress.md` to understand current state.
2. Read `.ai-frame/decisions.md` for past architectural decisions.
3. Read `.ai-frame/architecture.md` for system design details.
4. Check `.ai-frame/sessions/` for recent session summaries.

{extra_context_block}\
"""

ARCHITECTURE_MD_TEMPLATE = """\
# Architecture Notes — {project_name}

> Keep this file updated as the system evolves. Last updated: {date}

## System Design

<!-- Describe the high-level architecture here. Diagrams as ASCII or Mermaid are welcome. -->

## Key Components

<!-- List major modules, services, or packages and their responsibilities. -->

## Data Flow

<!-- How does data move through the system? -->

## External Dependencies

<!-- Third-party services, APIs, databases, queues, etc. -->

## Known Trade-offs

<!-- Deliberate design trade-offs and their justifications. -->
"""

DECISIONS_MD_TEMPLATE = """\
# Architecture Decision Log — {project_name}

> Record significant decisions here. Format: date, decision, reasoning, alternatives considered.

## Template

```
### YYYY-MM-DD — <short title>
**Decision:** ...
**Reasoning:** ...
**Alternatives considered:** ...
**Consequences:** ...
```

---

### {date} — Project initialised with AI Frame
**Decision:** Set up AI Frame context management framework.
**Reasoning:** Reduce token usage across Claude Code sessions by persisting context locally.
**Alternatives considered:** None at this stage.
**Consequences:** Sessions should be started/ended with session_manager.py to keep context current.
"""

PROGRESS_MD_TEMPLATE = """\
# Current Progress — {project_name}

> Update this after each session. This is the first thing Claude reads. Last updated: {date}

## Status

**Phase:** {current_phase}

## What's Working

<!-- List features / components that are complete and stable. -->

## In Progress

<!-- What is actively being built right now? -->

## Next Up

<!-- Immediate next tasks in priority order. -->

## Blockers

<!-- Anything blocking progress. Remove when resolved. -->

## Recent Decisions

<!-- Latest significant decisions (link to decisions.md for full log). -->
"""

CONFIG_TEMPLATE = {
    "version": "1.0",
    "project_name": "",
    "created": "",
    "project_type": "",
    "language": "",
    "framework": "",
    "architecture": "",
    "testing_strategy": "",
    "current_phase": "",
    "team_size": "",
}

# ─── UI Helpers ───────────────────────────────────────────────────────────────

CYAN   = "\033[96m"
YELLOW = "\033[93m"
GREEN  = "\033[92m"
RESET  = "\033[0m"
BOLD   = "\033[1m"


def header(text: str) -> None:
    width = 60
    print(f"\n{CYAN}{'─' * width}{RESET}")
    print(f"{BOLD}{CYAN}  {text}{RESET}")
    print(f"{CYAN}{'─' * width}{RESET}\n")


def ask_text(label: str, placeholder: str = "", optional: bool = False) -> str:
    hint = f"  {YELLOW}({placeholder}){RESET}" if placeholder else ""
    opt  = f" {YELLOW}[optional]{RESET}" if optional else ""
    while True:
        raw = input(f"{BOLD}{label}{opt}{RESET}{hint}\n  > ").strip()
        if raw:
            return raw
        if optional:
            return ""
        print(f"  {YELLOW}This field is required.{RESET}")


def ask_choice(label: str, choices: list[str]) -> str:
    print(f"{BOLD}{label}{RESET}")
    for i, c in enumerate(choices, 1):
        print(f"  {CYAN}{i:>2}.{RESET} {c.replace('_', ' ')}")
    while True:
        raw = input(f"  > ").strip()
        if raw.isdigit() and 1 <= int(raw) <= len(choices):
            selected = choices[int(raw) - 1]
            print(f"  {GREEN}✓ {selected.replace('_', ' ')}{RESET}")
            return selected
        # Also accept typing the value directly
        matches = [c for c in choices if c.lower().startswith(raw.lower())]
        if len(matches) == 1:
            print(f"  {GREEN}✓ {matches[0].replace('_', ' ')}{RESET}")
            return matches[0]
        print(f"  {YELLOW}Enter a number 1–{len(choices)}.{RESET}")


def ask(q: dict) -> str:
    print()
    if q["type"] == "choice":
        return ask_choice(q["label"], q["choices"])
    return ask_text(
        q["label"],
        placeholder=q.get("placeholder", ""),
        optional=q.get("optional", False),
    )

# ─── File Generation ──────────────────────────────────────────────────────────

def bullet_list(text: str, fallback: str = "_None specified._") -> str:
    if not text:
        return fallback
    items = [i.strip() for i in text.split(",") if i.strip()]
    return "\n".join(f"- {item}" for item in items)


def build_claude_md(answers: dict) -> str:
    runtime_line = (
        f"\n- **Runtime/version:** {answers['runtime_version']}"
        if answers.get("runtime_version")
        else ""
    )
    return CLAUDE_MD_TEMPLATE.format(
        project_name=answers["project_name"],
        date=datetime.now().strftime("%Y-%m-%d"),
        project_type=answers["project_type"].replace("_", " "),
        language=answers["language"],
        runtime_line=runtime_line,
        frameworks=answers.get("frameworks") or "None",
        architecture=answers["architecture"].replace("_", " "),
        current_phase=answers["current_phase"].replace("_", " "),
        team_size=answers["team_size"].replace("_", " "),
        description=answers["description"],
        priorities_block=bullet_list(answers.get("priorities", "")),
        testing_strategy=answers["testing_strategy"].replace("_", " "),
        code_style=answers.get("code_style") or "Not specified",
        constraints_block=bullet_list(answers.get("constraints", ""), "_No hard constraints specified._"),
        avoid_block=bullet_list(answers.get("avoid", ""), "_None specified._"),
        extra_context_block=(
            f"\n## Extra Context\n\n{answers['extra_context']}\n"
            if answers.get("extra_context")
            else ""
        ),
    )


def write_project_files(project_dir: Path, answers: dict) -> None:
    ai_frame_dir = project_dir / ".ai-frame"
    sessions_dir = ai_frame_dir / "sessions"

    ai_frame_dir.mkdir(parents=True, exist_ok=True)
    sessions_dir.mkdir(parents=True, exist_ok=True)

    date = datetime.now().strftime("%Y-%m-%d")
    name = answers["project_name"]

    # CLAUDE.md
    claude_md = project_dir / "CLAUDE.md"
    if claude_md.exists():
        backup = project_dir / f"CLAUDE.md.bak.{datetime.now().strftime('%Y%m%d%H%M%S')}"
        claude_md.rename(backup)
        print(f"  Existing CLAUDE.md backed up to {backup.name}")
    claude_md.write_text(build_claude_md(answers), encoding="utf-8")
    print(f"  {GREEN}✓{RESET} CLAUDE.md")

    # .ai-frame/config.json
    config = {**CONFIG_TEMPLATE}
    config.update({
        "project_name": name,
        "created": date,
        "project_type": answers["project_type"],
        "language": answers["language"],
        "runtime_version": answers.get("runtime_version", ""),
        "framework": answers.get("frameworks", ""),
        "architecture": answers["architecture"],
        "testing_strategy": answers["testing_strategy"],
        "current_phase": answers["current_phase"],
        "team_size": answers["team_size"],
    })
    (ai_frame_dir / "config.json").write_text(
        json.dumps(config, indent=2), encoding="utf-8"
    )
    print(f"  {GREEN}✓{RESET} .ai-frame/config.json")

    # .ai-frame/architecture.md
    (ai_frame_dir / "architecture.md").write_text(
        ARCHITECTURE_MD_TEMPLATE.format(project_name=name, date=date),
        encoding="utf-8",
    )
    print(f"  {GREEN}✓{RESET} .ai-frame/architecture.md")

    # .ai-frame/decisions.md
    (ai_frame_dir / "decisions.md").write_text(
        DECISIONS_MD_TEMPLATE.format(project_name=name, date=date),
        encoding="utf-8",
    )
    print(f"  {GREEN}✓{RESET} .ai-frame/decisions.md")

    # .ai-frame/progress.md
    (ai_frame_dir / "progress.md").write_text(
        PROGRESS_MD_TEMPLATE.format(
            project_name=name,
            date=date,
            current_phase=answers["current_phase"].replace("_", " "),
        ),
        encoding="utf-8",
    )
    print(f"  {GREEN}✓{RESET} .ai-frame/progress.md")

# ─── Main ─────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description="AI Frame — initialise a Claude Code project context"
    )
    parser.add_argument(
        "--project-dir",
        default=".",
        help="Path to the project directory (default: current directory)",
    )
    args = parser.parse_args()

    project_dir = Path(args.project_dir).resolve()
    if not project_dir.exists():
        print(f"Error: directory does not exist: {project_dir}")
        sys.exit(1)

    header("AI Frame — Project Initialisation Wizard")
    print(f"  Target project directory: {CYAN}{project_dir}{RESET}")
    print("  Answer the questions below to generate your CLAUDE.md master prompt.")
    print("  Press Ctrl-C at any time to abort without writing files.\n")

    answers: dict[str, str] = {}
    try:
        for q in QUESTIONS:
            answers[q["key"]] = ask(q)
    except KeyboardInterrupt:
        print(f"\n\n  {YELLOW}Aborted. No files written.{RESET}\n")
        sys.exit(0)

    header("Generating project files")
    write_project_files(project_dir, answers)

    header("Done!")
    print(f"  Your project is ready. Next steps:\n")
    print(f"  1. Open {CYAN}{project_dir}{RESET} in Claude Code (it will auto-load CLAUDE.md)")
    print(f"  2. Fill in {CYAN}.ai-frame/architecture.md{RESET} with system design details")
    print(f"  3. Run {CYAN}session_manager.py start{RESET} at the beginning of each session")
    print(f"  4. Run {CYAN}session_manager.py end{RESET} at the end of each session\n")


if __name__ == "__main__":
    main()
